import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import config from 'config';
import { handleEndpointError } from '../utils/errorHandler';

const authConfig = config.get('authConfig');
//check the jwt authefication token generated by sending a post request with a client data to a /login endpoint
export const checkAuth = (req: Request, res: Response, next: NextFunction) => {
  try {
    const token = req.headers['token'] || '';
    const { id } = jwt.verify(token, authConfig.secret);
    //@ts-ignore
    req.client = { id };
    next();
  } catch (e) {
    handleEndpointError(e, res, 401);
  }
};
